# -*- coding: utf-8 -*-
"""code1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZsFGMOniE4HQdPuSWySu1I9aVX6aXAyk
"""

# ============================================================
# PROFESSIONAL FARMER DECISION SUPPORT SYSTEM (STREAMLIT)
# Road Distance Version (No Straight Line Fallback)
# ============================================================

import streamlit as st
import pandas as pd
import numpy as np
import requests
import folium
import plotly.express as px
from streamlit.components.v1 import html

st.set_page_config(page_title="Farmer DSS", layout="wide")
st.title("🍋 Professional Farmer Decision Support System")

# ================= CONFIG =================
RADIUS_KM = 80
TRANSPORT_RATE_PER_10KM_PER_TONNE = 2000
SPOILAGE_PER_10KM = 0.004
HANDLING_RISK = 0.002

# ================= LOAD DATA =================
@st.cache_data
def load_data():
    villages = pd.read_csv("Village data.csv")
    prices = pd.read_csv("cleaned_price_data.csv")
    geo = pd.read_csv("cleaned_geo_locations.csv")
    processing = pd.read_csv("cleaned_processing_facilities.csv")
    pulp = pd.read_csv("Pulp_units_merged_lat_long.csv")
    pickle_units = pd.read_csv("cleaned_pickle_units.csv")
    local_export = pd.read_csv("cleaned_local_export.csv")
    abroad_export = pd.read_csv("cleaned_abroad_export.csv")

    for df in [villages, prices, geo, processing,
               pulp, pickle_units, local_export, abroad_export]:
        df.columns = df.columns.str.strip().str.lower()

    return villages, prices, geo, processing, pulp, pickle_units, local_export, abroad_export


villages, prices, geo, processing, pulp, pickle_units, local_export, abroad_export = load_data()

# ================= HELPER =================
def detect_cols(df):
    name, lat, lon = None, None, None
    for c in df.columns:
        if "lat" in c:
            lat = c
        if "lon" in c:
            lon = c
        if any(x in c for x in ["name","firm","facility","hub","market","place","panchayat","village"]):
            name = c
    return name, lat, lon

# ================= SIDEBAR =================
st.sidebar.header("Farmer Input Panel")

village_input = st.sidebar.text_input("Enter Village Name")
variety = st.sidebar.selectbox(
    "Select Mango Variety",
    ["Banganapalli","Totapuri","Neelam","Rasalu"]
)

TONNES = st.sidebar.number_input(
    "Enter Quantity (Tonnes)",
    min_value=1,
    max_value=100,
    value=10
)

run = st.sidebar.button("Run Smart Analysis")

# ================= VARIETY LOGIC =================
variety_acceptance = {
    "Mandi": ["Banganapalli","Totapuri","Neelam","Rasalu"],
    "Processing": ["Totapuri","Neelam"],
    "Pulp": ["Totapuri"],
    "Pickle": ["Totapuri","Rasalu"],
    "Local Export": ["Banganapalli"],
    "Abroad Export": ["Banganapalli"]
}

category_params = {
    "Mandi": {"margin":0},
    "Processing": {"margin":0.03},
    "Pulp": {"margin":0.04},
    "Pickle": {"margin":0.025},
    "Local Export": {"margin":0.05},
    "Abroad Export": {"margin":0.07},
}

# ================= RUN =================
if run:

    v_name_col, v_lat_col, v_lon_col = detect_cols(villages)
    villages[v_name_col] = villages[v_name_col].str.lower()

    if village_input.lower() not in villages[v_name_col].values:
        st.error("Village not found in dataset")
        st.stop()

    village = villages[villages[v_name_col] == village_input.lower()].iloc[0]
    v_lat = village[v_lat_col]
    v_lon = village[v_lon_col]

    # ================= BASE PRICE =================
    mandi_data = prices.merge(geo, on="market", how="left")
    mandi_data = mandi_data.dropna(subset=["latitude","longitude"])

    mandi_data["approx"] = (
        (mandi_data["latitude"] - v_lat)**2 +
        (mandi_data["longitude"] - v_lon)**2
    )

    nearest = mandi_data.loc[mandi_data["approx"].idxmin()]
    base_price = nearest["today_price(rs/kg)"]

    st.subheader("Nearest Market")
    st.write("Market:", nearest["market"])
    st.write("Base Price (₹/kg):", base_price)

    # ================= COLLECT ALL OPTIONS =================
    def collect_all(df, category):
        if variety not in variety_acceptance[category]:
            return pd.DataFrame()

        name_col, lat_col, lon_col = detect_cols(df)
        rows = []

        for _, row in df.iterrows():
            if pd.notnull(row[lat_col]) and pd.notnull(row[lon_col]):
                rows.append({
                    "Type":category,
                    "Name":row[name_col],
                    "Lat":row[lat_col],
                    "Lon":row[lon_col]
                })

        return pd.DataFrame(rows)

    df_all = pd.concat([
        collect_all(mandi_data,"Mandi"),
        collect_all(processing,"Processing"),
        collect_all(pulp,"Pulp"),
        collect_all(pickle_units,"Pickle"),
        collect_all(local_export,"Local Export"),
        collect_all(abroad_export,"Abroad Export")
    ], ignore_index=True)

    results = []

    # ================= ROAD DISTANCE LOOP =================
    for _, row in df_all.iterrows():

        try:
            url = (
                f"https://router.project-osrm.org/route/v1/driving/"
                f"{v_lon},{v_lat};{row['Lon']},{row['Lat']}?overview=false"
            )

            response = requests.get(url, timeout=10)
            data = response.json()

            if response.status_code != 200 or "routes" not in data:
                continue

            km = data["routes"][0]["distance"] / 1000

        except:
            continue  # skip if routing fails

        if km > RADIUS_KM:
            continue

        cat = row["Type"]
        margin = category_params[cat]["margin"]

        adjusted_price = base_price * (1 + margin)
        revenue = adjusted_price * 1000 * TONNES
        transport = (km/10) * TRANSPORT_RATE_PER_10KM_PER_TONNE * TONNES

        spoilage_risk = SPOILAGE_PER_10KM * (km/10)
        risk_rate = spoilage_risk + HANDLING_RISK
        risk_cost = revenue * risk_rate

        net_profit = revenue - transport - risk_cost

        results.append({
            "Type":cat,
            "Name":row["Name"],
            "Distance_km":round(km,2),
            "Revenue":round(revenue,2),
            "Transport":round(transport,2),
            "Risk_Cost":round(risk_cost,2),
            "Net_Profit":round(net_profit,2),
            "Lat":row["Lat"],
            "Lon":row["Lon"]
        })

    if len(results) == 0:
        st.error("No road routes found within radius.")
        st.stop()

    df = pd.DataFrame(results)
    df_top10 = df.sort_values("Distance_km").head(10)

    st.subheader("Top 10 Closest Options")
    st.dataframe(df_top10)

    # ================= BEST =================
    best = df_top10.loc[df_top10["Net_Profit"].idxmax()]
    st.success("🏆 Most Profitable Option")
    st.write(best)

    # ================= PROFIT GRAPH =================
    fig = px.bar(df_top10, x="Name", y="Net_Profit",
                 title="Profit Comparison")
    st.plotly_chart(fig, use_container_width=True)

    # ================= MAP =================
    m = folium.Map(location=[v_lat, v_lon], zoom_start=10)
    folium.Marker([v_lat, v_lon], popup="Village").add_to(m)

    for _, row in df_top10.iterrows():
        folium.Marker(
            [row["Lat"], row["Lon"]],
            popup=f"{row['Name']} ({row['Type']})"
        ).add_to(m)

    html(m._repr_html_(), height=600)